./submit.csh /home/sixie/CMSSW_2_1_11/src/MitHiggs/macros/runMacros/runHWWEventSelectionOptimizationTreeCreatorMod.C+ /home/mitprod/catalog/mit filler/006 s8-h130ww2l-id9 HWWEventSelectionOptimizationTree /server/02a/sixie/ntuples -1 
./submit.csh /home/sixie/CMSSW_2_1_11/src/MitHiggs/macros/runMacros/runHWWEventSelectionOptimizationTreeCreatorMod.C+ /home/mitprod/catalog/mit filler/006 s8-h150ww2l-id9 HWWEventSelectionOptimizationTree /server/02a/sixie/ntuples -1 
./submit.csh /home/sixie/CMSSW_2_1_11/src/MitHiggs/macros/runMacros/runHWWEventSelectionOptimizationTreeCreatorMod.C+ /home/mitprod/catalog/mit filler/006 s8-h160ww2l-id9 HWWEventSelectionOptimizationTree /server/02a/sixie/ntuples -1 
./submit.csh /home/sixie/CMSSW_2_1_11/src/MitHiggs/macros/runMacros/runHWWEventSelectionOptimizationTreeCreatorMod.C+ /home/mitprod/catalog/mit filler/006 s8-h170ww2l-id9 HWWEventSelectionOptimizationTree /server/02a/sixie/ntuples -1 
./submit.csh /home/sixie/CMSSW_2_1_11/src/MitHiggs/macros/runMacros/runHWWEventSelectionOptimizationTreeCreatorMod.C+ /home/mitprod/catalog/mit filler/006 s8-h200ww2l-id9 HWWEventSelectionOptimizationTree /server/02a/sixie/ntuples -1 
./submit.csh /home/sixie/CMSSW_2_1_11/src/MitHiggs/macros/runMacros/runHWWEventSelectionOptimizationTreeCreatorMod.C+ /home/mitprod/catalog/mit filler/006 s8-h500ww2l-id9 HWWEventSelectionOptimizationTree /server/02a/sixie/ntuples -1 
./submit.csh /home/sixie/CMSSW_2_1_11/src/MitHiggs/macros/runMacros/runHWWEventSelectionOptimizationTreeCreatorMod.C+ /home/mitprod/catalog/mit filler/006 f8-ttbar-mg-id9 HWWEventSelectionOptimizationTree /server/02a/sixie/ntuples -1 
./submit.csh /home/sixie/CMSSW_2_1_11/src/MitHiggs/macros/runMacros/runHWWEventSelectionOptimizationTreeCreatorMod.C+ /home/mitprod/catalog/mit filler/006 f8-wjets-mg-id9 HWWEventSelectionOptimizationTree /server/02a/sixie/ntuples -1 
./submit.csh /home/sixie/CMSSW_2_1_11/src/MitHiggs/macros/runMacros/runHWWEventSelectionOptimizationTreeCreatorMod.C+ /home/mitprod/catalog/mit filler/006 s8-ww2l-id9 HWWEventSelectionOptimizationTree /server/02a/sixie/ntuples -1 
./submit.csh /home/sixie/CMSSW_2_1_11/src/MitHiggs/macros/runMacros/runHWWEventSelectionOptimizationTreeCreatorMod.C+ /home/mitprod/catalog/mit filler/006 s8-wz3l-id9 HWWEventSelectionOptimizationTree /server/02a/sixie/ntuples -1 
./submit.csh /home/sixie/CMSSW_2_1_11/src/MitHiggs/macros/runMacros/runHWWEventSelectionOptimizationTreeCreatorMod.C+ /home/mitprod/catalog/mit filler/006 s8-zz4l-id9 HWWEventSelectionOptimizationTree /server/02a/sixie/ntuples -1 
./submit.csh /home/sixie/CMSSW_2_1_11/src/MitHiggs/macros/runMacros/runHWWEventSelectionOptimizationTreeCreatorMod.C+ /home/mitprod/catalog/mit filler/006 f8-vqq-mg-id9 HWWEventSelectionOptimizationTree /server/02a/sixie/ntuples -1 
./submit.csh /home/sixie/CMSSW_2_1_11/src/MitHiggs/macros/runMacros/runHWWEventSelectionOptimizationTreeCreatorMod.C+ /home/mitprod/catalog/mit filler/006 f8-zjets-mg-id9 HWWEventSelectionOptimizationTree /server/02a/sixie/ntuples -1 

