#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-wm-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 0
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-we-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 1
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-wt-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 2
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-wjets-mg-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 3
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-ttbar-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 4
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 f8-ttbar-mg-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 5
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-zmm-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 6
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-zee-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 7
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-ztt-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 8
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-zjets-mg-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 9
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-vqq-mg-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 10
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-qcdem_20_30-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 11
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-qcdem_30_80-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 12
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-qcdem_80_170-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 13
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-qcdbc_20_30-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 14
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-qcdbc_30_80-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 15
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-qcdbc_80_170-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 16
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-incppmux-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 17
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-incmu_15-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 18
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-ww2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 19
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-wz3l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 20
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-wzinc-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 21
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-zz2l2n-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 22
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-zz4l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 23
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-h130ww2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 24
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-h150ww2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 25
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-h160ww2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 26
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-h170ww2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 27
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-h200ww2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 28
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-h500ww2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 29
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-sitop-sch-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 30
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-sitop-tch-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 31
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-sitop-twch-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 32
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-zmm-m20-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 33
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-zee-m20-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 34
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-ztt-m20-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 35
./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 s8-gg-ww-4l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 36
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 w09-fast-wlnu-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 100
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 w09-fast-tt-2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 101
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 w09-fast-z2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 102
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 w09-fast-qcd20_5000-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 103
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 w09-fast-ww-2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 104
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 w09-fast-wz-2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 105
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 w09-fast-zz2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 106
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 w09-fast-hww130-2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 107
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 w09-fast-hww150-2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 108
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 w09-fast-hww160-2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 109
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 w09-fast-hww170-2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 110
#./submit.csh /home/sixie/CMSSW_2_2_7/src/MitHiggs/macros/runMacros/runHiggsNtupleMaker.C+ /home/mitprod/catalog/mit filler/008 w09-fast-hww200-2l-id11 noskim HiggsNtuple /server/04a/sixie/HiggsNtuples 111
